COLUNA_PRODUCT_ID = "product_id"
COLUNA_DATA = "data"
COLUNA_HORA = "hora"
COLUNA_DEPARTAMENTO = "departamento"
COLUNA_LATITUDE = "geolocation_lat"
COLUNA_LONGITUDE = "geolocation_lng"
PREFIXO_CEP_RAW = "geolocation_zip_code_prefix"
